{% set name = "precession" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 566c6b32761db097d1a82efb6825c05dc004abc99dd7524e35348e6a3728f4bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - parmap >=1.5.1
    - python >=3.6
    - scipy

test:
  imports:
    - precession
    - precession.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dgerosa/precession/
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: Dynamics of precessing black-hole binaries
  doc_url: https://pypi.org/project/precession/
  dev_url: https://github.com/dgerosa/precession/

extra:
  recipe-maintainers:
    - chadhenshaw
