{% set name = "precession" %}
{% set version = "2.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 59b7f2c45dc1976faab2f9ce818c7d2bcef13c96745b284c851bfea1e258636d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - parmap >=1.5.1
    - python >=3.6
    - scipy

test:
  imports:
    - precession
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/dgerosa/precession/"
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE.txt
  summary: "Dynamics of precessing black-hole binaries"
  doc_url: https://pypi.org/project/precession/
  dev_url: https://github.com/dgerosa/precession/

extra:
  recipe-maintainers:
    - chadhenshaw
